# These are supported funding model platforms

github: [mazbah229]
buy_me_a_coffee: mazbah229
custom: ['https://www.supportkori.com/mazbah229', 'https://pixonexit.com/bank-details', 'https://pixonexit.com/bank-details/#MFS']
